repos:
  - repo: local
    hooks:
      - id: ruff check
        name: ruff check
        entry: ./scripts/environments/ruff-check.sh
        require_serial: true
        language: system
        types_or: [python, pyi, jupyter]
      - id: ruff format
        name: ruff format
        entry: ./scripts/environments/ruff-format.sh
        require_serial: true
        language: system
        types_or: [python, pyi, jupyter]
      - id: pytest
        name: pytest
        entry: ./scripts/environments/pytest.sh
        require_serial: true
        language: system
        types_or: [python, pyi, jupyter]
      - id: mypy
        name: mypy
        entry: ./scripts/environments/mypy.sh
        require_serial: true
        language: system
        types_or: [python, pyi, jupyter]
